version: "3.3"
services:
  jenkins:
    image: mrchecker/mrchecker-jenkins:v1.1.2
    ports:
      - "8888:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins:/var/jenkins_home
    build:
      context: .
      dockerfile: dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1m
        max_attempts: 5
        window: 3m
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
        - "4444:4444"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1m
        max_attempts: 5
        window: 3m
  selenium-firefox:
    image: selenium/node-firefox:3.141.59
    volumes:
        - /dev/shm:/dev/shm
    depends_on:
        - selenium-hub
    environment:
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1m
        max_attempts: 5
        window: 3m
  selenium-opera:
    image: selenium/node-opera:3.141.59
    volumes:
        - /dev/shm:/dev/shm
    depends_on:
        - selenium-hub
    environment:
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
    deploy:
      replicas: 0
  selenium-chrome:
    image: selenium/node-chrome:3.141.59
    volumes:
        - /dev/shm:/dev/shm
    depends_on:
        - selenium-hub
    environment:
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
    deploy:
      replicas: 0
  reverse-proxy:
    #build: 'reverse-proxy/'
    restart: always
    #container_name: 'mts_reverse_proxy'
    image: docker.pkg.github.com/devonfw/my-thai-star/reverse-proxy   #docker pull docker.pkg.github.com/devonfw/my-thai-star/reverse-proxy:latest
    networks:
      - my-thai-star
    ports:
      - '8081:80'
    deploy:
      replicas: 0
  angular:
    #build: 'angular/'
    restart: always
    #container_name: 'mts_angular'
    image: docker.pkg.github.com/devonfw/my-thai-star/angular:latest #docker pull docker.pkg.github.com/devonfw/my-thai-star/angular:latest
    networks:
      - my-thai-star
    deploy:
      replicas: 0
  java:
    #build: 'java/'
    restart: always
    #container_name: 'mts_java'
    image: docker.pkg.github.com/devonfw/my-thai-star/java:latest #docker pull docker.pkg.github.com/devonfw/my-thai-star/java:latest
    networks:
      - my-thai-star
    deploy:
      replicas: 0
networks:
  my-thai-star:
    driver: bridge
