FROM jenkins/jenkins:2.409


USER root
RUN apt-get update \
    && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" \
    && apt-get update \
    && apt-get install -y docker-ce docker-ce-cli containerd.io 
RUN usermod -a -G docker jenkins
#TODO review commented out code
#&& chown /var/run/docker.sock docker:docker
#USER jenkins
COPY ./plugins.txt /var/jenkins_home
#COPY ./plugins.txt /usr/share/jenkins/ref/plugins.txt
#RUN ls /var/jenkins_home
RUN /bin/jenkins-plugin-cli -f /var/jenkins_home/plugins.txt
