env.module = "${JOB_NAME}".split('/')[0]
env.workspace = "mrchecker-framework-modules"
pipeline{
	agent {docker {image 'marzepka/mrchecker:v1.1.3'}}
	stages{
		stage('Build'){
			steps{
				echo "Building module ${env.module} and it's dependency"
				sh """
				cd ${env.workspace}
				mvn clean compile package install -DskipTests=true --projects ${env.module} --also-make
				"""
				//bulid this module and its dependencies deploy them to local repo
			}
		}
		stage('Test'){
			steps{
				echo "Testing ${env.module}"
				sh """
				cd ${env.workspace}
				mvn jacoco:prepare-agent verify -Dgroups=UnitTest,IntegrationTest --projects ${env.module} || exit 0
				"""
			}
		}
	}
	post{
		always{
			archiveArtifacts artifacts: "${env.workspace}/${env.module}/target/*.jar", fingerprint: true
			junit '**/surefire-reports/*.xml'
			jacoco()
		}
	}
}