env.module = "${JOB_NAME}".split('/')[1]
env.workspace = "mrchecker-framework-modules"
pipeline{
	agent {docker {image 'mrchecker/mrchecker:v1.1.3'}}
	stages{
		stage('Build'){
			steps{
				echo "Building module ${env.module} and it's dependency"
				sh """
				cd ${env.workspace}
				mvn clean compile package install -DskipTests=true --projects ${env.module} --also-make
				"""
				//bulid this module and its dependencies deploy them to local repo
			}
		}
		stage('Test'){
			steps{
				echo "Testing ${env.module}"
				sh """
				cd ${env.workspace}
				mvn jacoco:prepare-agent verify --projects ${env.module}
				"""
			}
		}
	}
	post{
		always{
			archiveArtifacts artifacts: "${env.workspace}/${env.module}/target/*.jar", fingerprint: true
			jacoco()
			junit testResults:'**/surefire-reports/*.xml', healthScaleFactor: 0.8 //as I set the junit treshold to 80%
		}
        success{
            script{
                def downstreamJob = "${JOB_NAME}".split('/')
                downstreamJob[0] = 'test'
                downstreamJob = downstreamJob.join('/')
                build job: downstreamJob, propagate: false, wait: false
            }
        }
	}
}

